# Site settings
author: Vladimir Jimenez
title: Vlad's Blog
header-img: img/home-bg.png
email: vladdaimpaler@protonmail.com
copyright_name: Vladimir Jimenez
description: > # this means to ignore newlines until "baseurl:"
  A Journey into Vlad's Mind
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  VladDaImpaler18

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
